name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm' # specify cache for pnpm
    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: latest
    - run: pnpm install # or `pnpm ci` if you have a pnpm-lock.yaml
    - run: pnpm run build --if-present
    - run: pnpm test